### ISSUE TITLE
Add an option for us to customize the length of the ruler

### ISSUE THREAD

**Issue by BCS1037** [MugishoMp/obsidian-editor-width-slider#1]
I think the current ruler is too long.

![image](https://github.com/MugishoMp/obsidian-editor-width-slider/assets/120721474/5cf47ca9-d67e-4ee9-83f4-5c8b462d6947)

Could you add an option for us to customize the length of the ruler?

**Comment by MugishoMp** [comment]
Hey thank you for the feedback! im on vacation right now but have already started working on this. I'll try to finish it as soon as possible when I am back.

**Comment by MugishoMp** [comment]
@BCS1037 I'm sorry that it took this long to get it fixed, so I'm hoping that you're still using this plugin. I have added a simple tab in settings that lets you customize the slider in real time. So please take a look at it: https://github.com/MugishoMp/obsidian-editor-width-slider/releases/tag/1.0.3

For now I'm going to close this issue but if you have any other suggestions regarding this setting please feel free to reopen this issue. But also feel free to open a new issue if you have any other suggestions. Thanks!
